### PR TITLE
Fixed share action for flash target

### PR DESCRIPTION
**Pull request by pozirk**
Simple URL sharing didn't work for me with Dialog and AppID.

### CODE REVIEW

**Comment by fbricker** [comment]
Hi, I'm testing this change and found some things we should consider before accepting it.

Currently, the URL used requires the APP ID:
```
https://www.facebook.com/dialog/feed?app_id='+Share.facebookAppID+'&description='+text+'&display=popup&caption='+subject+'&link='+url+redirectURI+'&images[]='+image;
```
This allows you to send some description text to facebook, like this:
```
https://www.facebook.com/dialog/feed?app_id=187231844810437&description=Estoy%20jugando%20%23Puralax.%20Pruébalo%20tu%20también.%20¡Es%20gratis!&display=popup&caption=¡Los%20colores%20cobran%20vida!&link=http%3A%2F%2Fwww.puralax.com&redirect_uri=http://www.puralax.com/shared/&images[]=http%3A%2F%2Fwww.puralax.com%2Fbig-icon.png
```
captura de pantalla 2015-07-09 a las 15 06 04

On the other hand, the modified method, does not requires you to have the APP ID, but sometimes does not display the submitted text:
```
https://www.facebook.com/sharer/sharer.php?u='+url+redirectURI+'&description='+text+'&display=popup&caption='+subject;
```
For example:
```
https://www.facebook.com/sharer/sharer.php?u=http://www.puralax.com&description=TESTING&display=popup&caption=TESTING
```
captura de pantalla 2015-07-09 a las 15 09 01


Maybe we should consider using the sharar.php only when no facebook APP ID is specified. What do you think?

**Comment by pozirk** [comment]
Yes, I think we should check for APP ID then and show dialog if we have it.

**Comment by fbricker** [comment]
Hi, I've added the proposed line to the code but including the if to check if you have facebook app id or not before opening the share URL.

I'm closing this PR as i manually added the lines on another commit.

Thanks! 👍

**Comment by pozirk** [comment]
Thank you!

**Pull request closed without merging**
